version: "3"

services:
  app:
    build:
      context: ./app
    ports:  
      - 8000:8000
    volumes:
      - ./app:/app
    command: > 
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: ./app
    command: celery -A core worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
    
volumes:
  postgres_data: