# Generated by Django 3.2.8 on 2021-10-26 08:08

from django.db import migrations, models
import recipe.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=recipe.utils.recipe_image_file_path),
        ),
    ]
